### ISSUE TITLE
Proxy Bug https://github.com/BuilderIO/gpt-crawler/pull/170 

### ISSUE THREAD

**Issue by frei-x** [BuilderIO/gpt-crawler#174]
npm start

 PlaywrightCrawler: Reclaiming failed request back to the list or queue TypeError: Cannot read properties of undefined (reading 'length')

 at ProxyConfiguration._handleCustomUrl \@crawlee\core\proxy_configuration.js:170:88

 at ProxyConfiguration.newUrl \proxy_configuration.js:156:21

**Comment by md-owes** [comment]
Just got the latest version and it started throwing this error. Temporarily reverting back to previous commit.

**Comment by steve8708** [comment]
thanks @md-owes for sharing, i have reverted the last commit that made the proxy change
